### ISSUE TITLE
Branch info?

### ISSUE THREAD

**Issue by Javid-k** [VinayKumarPamu/MyOwnProjects#1]
May I know which branch has latest all projects source code for practice and learning purpose.

**Comment by VinayKumarPamu** [comment]
Hi, every branch has a specific project except main branch, and master branch consists of banking service project (java-console based).

**Comment by vinaykumarpamu38** [comment]
> May I know which branch has latest all projects source code for practice and learning purpose.

Hi, every branch has a specific project except main branch, and master branch consists of banking service project (java-console based).

**Comment by Javid-k** [comment]
In console based Banking project, **GenericUtils.insert()** method is giving exception. please help
<img width="637" alt="image" src="https://github.com/VinayKumarPamu/MyOwnProjects/assets/154420447/627c3374-608d-419f-b424-f979a7ca6e60">

**Comment by vinaykumarpamu38** [comment]
Hi, hope you are using your DataBase connection credentials.

 And coming to your issue, here is the solution,,,,,
in GenericUtils.insert() :-  **accBal.setString(1, createAccount.getUserFirstName()+fName);**  make 0 as 1 in your code, _it is a basic syntax that in prepared statement, order of inserting data starts from 1._

In addition if you face any issue with banking services like balance enquiry or deposite etc. **(only if you face any issue)** change a thing in  GenericUtils.AccOp() as shown in image....

Thank you, Happy Coding.......
![check](https://github.com/VinayKumarPamu/MyOwnProjects/assets/148611831/ef13bd82-8103-4eee-bf0f-39e918317258)
![Update](https://github.com/VinayKumarPamu/MyOwnProjects/assets/148611831/466164da-c696-4408-8406-820613d3cadb)

**Comment by Javid-k** [comment]
Hi,

 I tried with the above updates, it worked! but still I notice there are some issues 
_1.Select your service
1.Balance Enquiry
2.Deposite Money
3.Withdraw Money
4.Transfer Money
**5.Transaction History** - This functionality is not able to take history from db.
6.LogOut_

**And** a minor change would be a case where user should be warned if the sender and receiver's account number is same!

**Comment by vinaykumarpamu38** [comment]
Hi, thank you for sharing!

I have updated the code in my **system**. 
**ping me in LinkedIn**  if you want and if you have any doubt...!!!

**LinkedIn** : https://www.linkedin.com/in/vinay-kumar-pamu

**Comment by Javid-k** [comment]
sure, Thank you.
